# theme: jekyll-theme-slate

# Site settings
title: start                     #你博客的标题
SEOTitle: 新博客 | New Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/sth.jpg     #显示在首页的背景图片
email: hll.cs1995@gmail.com    
description: "This is a blog for everything. "              #网站介绍
keyword: "Hanlin Lu, blog" #关键词
url: "https://hllmathcs.github.io/pw/"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "Continue..."
sidebar-avatar:/img/sth.jpg       # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

# SNS settings
RSS: false
facebook_username:     Hanlin Lu
zhihu_username:     Hammy
instagram_username: hanlin
github_username: hllmathcs